version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: MGEA (Make Gradle Executable Again)
          command: chmod +x gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew check 
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/outputs/apk
          destination: outputs/apk
      - store_test_results:
          path: app/build/test-results